# Generated by Django 4.1 on 2022-08-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_alter_ratings_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratings",
            options={"verbose_name_plural": "Ratings"},
        ),
    ]
