# Generated by Django 4.1 on 2022-08-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_song_rate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"verbose_name_plural": "Song"},
        ),
        migrations.AlterField(
            model_name="song",
            name="cover",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
