# Generated by Django 4.1 on 2022-08-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_artist_rate"),
        ("songs", "0004_remove_song_artist_song_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.ManyToManyField(
                blank=True, related_name="songs", to="artists.artist"
            ),
        ),
    ]
