# Generated by Django 4.1 on 2022-08-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0005_alter_song_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
