# Generated by Django 4.1 on 2022-08-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0007_alter_song_rate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"verbose_name_plural": "Songs"},
        ),
    ]
